<!--
<spam class="alinhamento_direita"><a href="<?=$this->url(array("controller"=>"adm-usuarios","action"=>"index"),null,true)?>"> Click aqui para ver os Usuários cadastrados</a></spam>
<br><br><br><br>-->
<form method="post" action="#">
    
    <select name="status_projeto_consulta" id="status_projeto_consulta" >
                        <option value="0" >Todos projetos</option>
                        <option value="2" >Aguardando aprovação</option>
                        <option value="4" >Ativo</option>
                        <option value="5" >Inativo</option>
                    </select>
    
    <input id="btnSelectStatus" type="submit" name="Enviar" value="Enviar"/><br><br>
</form>


<?php
    //'EMAIL' É O NOME DO LOGIN DO ADMINISTRADOR
    $usuario=$this->usuario->email;    
?>
<spam id="login" class="login"><a href="<?=$this->url(array("controller"=>"usuario","action"=>"sair"),null,true)?>">
           <?=$usuario?>, click aqui para sair     
    </a></spam><br><br>


<form name="form" method="post" action="<?=$this->url(array("controller"=>"adm-projetos","action"=>"atualiza"),null,true)?>">
    <table class="tftable">
    
    <tr>
        <th>Título</th>
        <th>Instituição</th>
        <th>Status do projeto</th>
        <th>PDF</th>
        <th>Alterar status</th>
    </tr>
   
   <?php
     foreach ($this->dados as $ln):
        ?>
    
    <tr>
        <td><?php echo $ln['titulo']  ?></td>
        <td><?php  echo $ln['nomeInst']  ?></td>
        <td><?php  echo $ln['status']  ?></td>
        <td><?php echo '<a href='. $this->url(array('controller' => 'projeto','action'=>'pdf','id' => $ln['id'] )).' target="_blank">' ?>  <img src="Imagens-projeto/Adobe.png" title="Gerar PDF completo" /></a></td>
        <td> 
            <input type='checkbox' name='checkbox_id[]' value="<?php echo $ln['id'] ?>">
            </td>
    </tr>
    
    <?php endforeach;?>
    
    </table><br>
    <a id="linkCbb" href="javascript:checkAll();">Marcar/Desmarcar todos</a><br><br>
        
    <select name="status_projeto" id="status_projeto" >
                        <option value="0" >Alterar status dos projetos selecionados</option>
                        <option value="4" >Ativo</option>
                        <option value="5" >Inativo</option>
                    </select>
    
    <input id="btn" type="submit"  value="Enviar"/><br><br>
</form>